#!/bin/bash

#Check environment
ls /Users/$(whoami)/Documents/C/out &> /dev/null
if test $? -ne 0; then
 mkdir -p /Users/$(whoami)/Documents/C/out
fi
ls /Users/$(whoami)/Documents/C/cpp &> /dev/null
if test $? -ne 0; then
 mkdir -p /Users/$(whoami)/Documents/C/cpp
fi

#Build from .c
ls /Users/$(whoami)/Documents/C/cpp/$1.c &> /dev/null
if test $? -ne 0; then
 echo "ERROR: No such file."
 exit 1
else
 gcc /Users/$(whoami)/Documents/C/cpp/$1.c -o /Users/$(whoami)/Documents/C/out/$1.out
fi
